### ISSUE TITLE
Does not work well on mobile devices

### ISSUE THREAD

**Issue by sinano1107** [artcom/react-three-arjs#10]
This may be a problem with AR.js itself, but I checked with iPhone 13 pro and Google pixel 5 and the angle of the cube is strange
![IMG_0103](https://user-images.githubusercontent.com/45984123/161508267-8ee95b0a-7631-4ea2-870e-e84718cd7b4b.PNG)
![IMG_0104](https://user-images.githubusercontent.com/45984123/161508299-782f97ee-0022-4065-a17d-0d768e117bec.PNG)

**Comment by sinano1107** [comment]
I have the same problem with example

**Comment by kalwalt** [comment]
Hi @sinano1107 have you read this issue #4 ?

**Comment by sinano1107** [comment]
I am sorry. It was my lack of confirmation and I will close this issue.
Thank you.
