### ISSUE TITLE
Maintaining both `lib` and `src`

### ISSUE THREAD

**Issue by shubham1172** [artcom/react-three-arjs#14]
If `lib` is generated from `src` using `babel src --out-dir lib --source-maps`, is there a reason to maintain both of them?

**Comment by j-era** [comment]
Hi @shubham1172 Yes you're right, since we're now publishing an npm package we don't need this anymore. I'm going to remove the `lib` folder from git tracking.

**Comment by j-era** [comment]
Done in 2ce1021dd58cc19032568be5d5c3e22536a6d845

**Comment by shubham1172** [comment]
Thanks @j-era, but package.json seems to be pointing to `lib` instead of `src`. Can you please check that?
