### ISSUE TITLE
next.js support

### ISSUE THREAD

**Issue by kelokchan** [artcom/react-three-arjs#38]
I'm trying to use this library on a next.js project but I'm getting the following error when trying to import `ARCanvas`

```
Failed to compile
./node_modules/@artcom/react-three-arjs/lib/ar/ar.js:3:0
Module not found: Can't resolve 'core-js/modules/es.symbol.to-primitive.js'
```

Has anyone faced similar issues?

**Comment by HerpGuy88** [comment]
> I'm trying to use this library on a next.js project but I'm getting the following error when trying to import `ARCanvas`
> 
> ```
> Failed to compile
> ./node_modules/@artcom/react-three-arjs/lib/ar/ar.js:3:0
> Module not found: Can't resolve 'core-js/modules/es.symbol.to-primitive.js'
> ```
> 
> Has anyone faced similar issues?

Did you ever solve this issue? I'm having the same problem.
