### ISSUE TITLE
Barcode markers

### ISSUE THREAD

**Issue by mpopovs** [artcom/react-three-arjs#41]
Hello, I try to use 3 x 3 barcode markers, but no any luck.
`import { ARCanvas, ARMarker } from "@artcom/react-three-arjs";
import { useState } from "react";
import { createRoot } from "react-dom/client";
import { Model } from "./models/Duck";

function Box() {
  const [selected, setSelected] = useState(false);

  return (
    <mesh onClick={() => setSelected(!selected)}>
      <boxGeometry args={[1, 1, 1]} />
      <meshStandardMaterial color={selected ? "yellow" : "hotpink"} />
    </mesh>
  );
}

createRoot(document.getElementById("root")).render(
  
  <ARCanvas
    onCameraStreamReady={() => console.log("Camera stream ready")}
    onCameraStreamError={() => console.error("Camera stream error")}
    sourceType={"webcam"}
    matrixCodeType = {"3x3"} 
    detectionMode = {"mono_and_matrix"} 
    cameraParametersUrl = {"/data/camera_para.dat"}  
    patternRatio = {0.5}     
                        
  >
 
    <ambientLight />
    <pointLight position={[10, 10, 0]} intensity={10.0} />
    <ARMarker
      debug={true}
      params={{ smooth: true }}
      type={'barcode'}
      barcodeValue ={'31'}
      
      onMarkerFound={() => {
        console.log("Marker Found");
      }}
    >
      <Model />
    </ARMarker>
    {/* <ARMarker
      debug={true}
      params={{ smooth: true }}
      type={"pattern"}
      patternUrl={"data/patt.kanji"}
      onMarkerFound={() => {
        console.log("Marker Found");
      }}
    >
      <Box />
    </ARMarker> */}
  </ARCanvas>
);
`

**Comment by kalwalt** [comment]
Hi @mpopovs how did you solved?

**Comment by mpopovs** [comment]
Hi, @kalwalt yes, there was my mistake. But now now I have new problem. When use 'useState' onMarkersFound prop on ARMarker app broke after marker get found.

**Comment by mpopovs** [comment]
Hi @kalwalt , I solve by reading documentation :) 
`<ARMarker
      params={{ smooth: true }}
      type={"barcode"}
      barcodeValue ={31}
      onMarkerFound={() => {
        console.log("Marker Found"); 
      }}
    >`  
just need to use integer not string in barcodeValue!

**Comment by kalwalt** [comment]
> When use 'useState' onMarkersFound prop on ARMarker app broke after marker get found.

I think you should open a new issue for this. I'm not the maintainer of this project maybe @artcom @j-era may help you.
