### ISSUE TITLE
Example doesn't run without cert.pem

### ISSUE THREAD

**Issue by aVileBroker** [artcom/react-three-arjs#7]
From a fresh install, the example isn't runnable.

Firstly, http-server needs to be added to the package dependencies
Secondly, the start command which uses http-server also specifies a cert.pem file which isn't in the repo

**Comment by j-era** [comment]
Right, thank you! Fixed it in https://github.com/artcom/react-three-arjs/commit/f905ebf497fbbc7b89cfdea51c9dbb1c506eef63
